# Generated by Django 4.2 on 2024-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
